services:
  postgres:
    image: postgres:17.2-alpine
    container_name: tsunami-postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${PG_DB_USER} -d ${PG_DB_NAME}'" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - network
  mariadb:
    image: mariadb:5.5
    container_name: tsunami-mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e4r
      - TZ=Asia/Bangkok
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - network
  adminer:
    image: adminer
    container_name: tsunami-adminer
    restart: always
    ports:
      - 8001:8080
    networks:
      - network
  api:
    build: .
    container_name: tsunami-api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    networks:
      - network
volumes:
  postgres-data:
    driver: local
  mariadb-data:
    driver: local
networks:
  network:
